/**
 * Metacore IoT Object Storage API
 * Metacore Object Storage - IOT Core Services
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Sensors { 
    id?: string;
    measurementName?: string;
    measures?: Array<string>;
    name: string;
    sensorBrand?: string;
    sensorModel?: string;
}